# This is a basic workflow to help you started with Actions.
name: wizards-session-3
# Controls when the action will run.
on: 
 [workflow_dispatch]
# A workflow run is made up of one or more jobs
jobs:
  # This workflow contains a single job called "build"
  build: 
    # Runner type
    runs-on: self-hosted
    # runs-on: ubuntu-latest
    # Steps represent a sequence of tasks
    permissions:
     id-token: write
     contents: read
    steps:
    - name: Checkout Git Repo
      uses: actions/checkout@v2
