# This is a basic workflow to help you get started with Actions.
name: wizards-session-3-1
# Controls when the action will run.
on: 
 [workflow_dispatch]
# A workflow run is made up of one or more jobs
jobs:
  # This workflow contains a single job called "build"
  build: 
    # Runner type
    runs-on: self-hosted
    # runs-on: ubuntu-latest
    # Steps represent a sequence of tasks
    permissions:
     id-token: write
     contents: read
    steps:
    - id: checkout
      name: Checkout Git Repo
      uses: actions/checkout@v2
    - id: fetch-secrets-1
      name: Fetch Secrets 1
      uses: akeyless-community/akeyless-github-action@v1.1.2
      with:
        access-id: '${{ secrets.ACCESS_ID }}'
        access-type: jwt
        export-secrets-to-outputs: true
        export-secrets-to-environment: true
        api-url: "https://csm.thalescryptolabs.com/akeyless-api/v2/"
        static-secrets: |
         - name: "MyFirstSecret"
           output-name: "my-first-secret"
    - id: use-secrets-1
      name: Use Secrets 1
      env:
       SECRET: ${{ env.my-first-secret }}      
      run: |
       # Use the secrets
       echo "Use Secrets 1"
       echo "Doing something with $SECRET"
    - id: use-secrets-2
      name: Use Secrets 2 
      run: |
       # Use the secrets
       echo "Use Secrets 2"
       echo "Doing something with ${{ steps.fetch-secrets-1.outputs.my-first-secret }}"      
       

        
        
      
