# This is a basic workflow to help you get started with Actions.
name: wizards-session-3-2
# Controls when the action will run.
on: 
 [workflow_dispatch]
# A workflow run is made up of one or more jobs
jobs:
  # This workflow contains a single job called "build"
  build: 
    # Runner type
    runs-on: self-hosted
    # runs-on: ubuntu-latest
    # Steps represent a sequence of tasks
    permissions:
     id-token: write
     contents: read
    steps:
    - id: checkout
      name: Checkout Git Repo
      uses: actions/checkout@v2
    - id: fetch-dynamic-secret
      name: Fetch Dynamic Secret
      uses: akeyless-community/akeyless-github-action@v1.1.2
      with:
        access-id: '${{ secrets.ACCESS_ID }}'
        access-type: jwt
        export-secrets-to-outputs: true
        export-secrets-to-environment: true
        api-url: "https://csm.thalescryptolabs.com/akeyless-api/v2/"
        dynamic-secrets: |
         - name: "thales-postgres-dynamic-secret"
           output-name: "dynamic-secret"
    - id: use-secret
      name: Use Secret
      run: |
       echo '${{ steps.fetch-dynamic-secret.outputs.dynamic-secret
       }}' | jq -r 'to_entries|map("\(.key|ascii_upcase)=\(.value|tostring)")|.[]'
          
           
